name: Build OpenWrt x86 v210207

on:
  push:
    tags:
      - v21.02.7  # 仅在 Push 该 Tag 时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your OpenWrt fork
      uses: actions/checkout@v4
      with:
        ref: v21.02.7  

    - name: Install dependencies
      run: |
        sudo apt update -y
        sudo apt install -y build-essential libncurses5-dev zlib1g-dev gawk git gettext \
          libssl-dev xsltproc wget unzip python3

    - name: Update and install feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure OpenWrt
      run: |
        make defconfig
        cat <<EOF > .config
        CONFIG_TARGET_x86=y
        CONFIG_TARGET_x86_64=y
        CONFIG_TARGET_ROOTFS_EXT4FS=y
        CONFIG_TARGET_ROOTFS_PARTSIZE=350
        CONFIG_GRUB_IMAGES=y
        CONFIG_GRUB_EFI_IMAGES=y
        CONFIG_GRUB_BOOTOPTS="rootfstype=ext4 rootwait"
        CONFIG_PACKAGE_luci=y
        CONFIG_PACKAGE_luci-app-webadmin=y
        CONFIG_PACKAGE_luci-app-firewall=y
        CONFIG_PACKAGE_luci-app-opkg=y
        CONFIG_PACKAGE_curl=y
        CONFIG_PACKAGE_htop=y
        CONFIG_PACKAGE_nano=y
        CONFIG_PACKAGE_wget=y
        CONFIG_PACKAGE_vnstat=y
        CONFIG_PACKAGE_bmon=y
        CONFIG_PACKAGE_iftop=y
        CONFIG_PACKAGE_iptables=y
        CONFIG_PACKAGE_ipset=y
        CONFIG_PACKAGE_tcpdump=y
        CONFIG_PACKAGE_kmod-fs-cifs=y
        CONFIG_PACKAGE_cifsmount=y
        CONFIG_PACKAGE_python3=y       
        CONFIG_PACKAGE_openssh-sftp-server=y
        CONFIG_PACKAGE_lrzsz=y
        CONFIG_PACKAGE_nfs-utils=y
        CONFIG_PACKAGE_kmod-fs-nfs-common=y
        CONFIG_PACKAGE_kmod-fs-nfs-v3=y
        CONFIG_PACKAGE_kmod-fs-nfs-v4=y
        CONFIG_PACKAGE_kmod-fs-nfs=y
        CONFIG_PACKAGE_dnsmasq=n      
        CONFIG_PACKAGE_dnsmasq_full=y
        CONFIG_PACKAGE_dnsmasq_full_ipset=y
        CONFIG_PACKAGE_dnsmasq_full_tftp=y
        CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
        CONFIG_PACKAGE_kmod-tun=y        
        CONFIG_PACKAGE_kmod-nf-conntrack-netlink=y
        EOF
        make defconfig

    - name: Compile OpenWrt
      run: |
        make download -j$(nproc)
        make -j$(nproc) || make -j1 V=s

    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-x86-firmware
        path: bin/targets/x86/64/*
